name: wav2lip

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ${{ github.event.inputs.os }}
            arch: [ amd64 ]
          - os: ${{ github.event.inputs.os }}
            arch: [ arm64 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Output OS and Arch
        run: |
          echo "OS: ${{ runner.os }}"
          echo "ARCH: ${{ runner.arch }}"

      - name: Git clone repo
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_REPO: ${{ secrets.GIT_REPO_TEST }}
        run: |
          git clone "https://${GIT_USER}:${GIT_PASS}@codeup.aliyun.com/${GIT_REPO}.git" code
          cd code
          ls -alh

